homeassistant:
  # Omitted values in this section will be auto detected using freegeoip.io

  # Location required to calculate the time the sun rises and sets
  latitude: 59.86972
  longitude: 10.81467

  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 160

  # 'metric' for Metric, 'imperial' for Imperial
  unit_system: metric

  # Pick yours from here:
  # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Oslo

  # Name of the location where Home Assistant is running
  name: Hjemme
  customize:
    cover.garasjen:
      device_class: garage
    device_tracker.galaxy_s10_getinternet_no:
      entity_picture: https://gravatar.com/avatar/47af7ccc79b304ab712dc1389ad1b37c
    device_tracker.samsunggalaxys7:
      entity_picture: /local/linn.jpeg
frontend:
config:
updater:
  include_used_components: true
prometheus:
http:
  base_url: homeassistant.ibidem.homeip.net
mqtt:
  broker: emrys
sensor:
  - platform: yr
    monitored_conditions:
      - symbol
      - temperature
      - precipitation
      - windSpeed
      - windDirection
cover:
  - platform: mqtt
    name: Garasjen
    command_topic: "trigger/Hypatia/garage_door"
    state_topic: "sensor/Hypatia/garage_door"
device_tracker:
  - platform: linksys_smart
    host: 192.168.1.1
    interval_seconds: 60
    new_device_defaults:
      track_new_devices: false
notify:
  - name: fast
    platform: pushover
    api_key: !secret pushover_api_key
    user_key: !secret pushover_user_key
  - name: slow
    platform: smtp
    server: smtp.getmail.no
    sender: mortenjo+home-assistant@ifi.uio.no
    recipient: mortenjo@ifi.uio.no
automation:
  - alias: Update notifications
    trigger:
      - platform: state
        entity_id: binary_sensor.updater
        from: 'off'
        to: 'on'
    action:
      service: notify.slow
      data_template:
        title: 'New Home Assistant Release'
        message: "Home Assistant {{ state_attr('binary_sensor.updater', 'newest_version') }} is available."
  - alias: Garage door is open after sunset
    trigger:
      platform: state
      entity_id: cover.garasjen
      to: 'open'
      for:
        minutes: 10
    condition:
      condition: sun
      after: sunset
    action:
      service: notify.fast
      data:
        message: 'The Garage door is open after sunset'
  - alias: Garage door is open when nobody is home
    trigger:
      platform: state
      entity_id: cover.garasjen
      to: 'open'
      for:
        minutes: 10
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: device_tracker.samsunggalaxys7
          state: not_home
        - condition: state
          entity_id: device_tracker.android477cc5c7413e351c
          state: not_home
    action:
      service: notify.fast
      data:
        message: 'The Garage door is open and nobody is home'
group:
  ' ':
    entities:
      - cover.garasjen
  Folk:
    entities:
      - device_tracker.samsunggalaxys7
      - device_tracker.galaxy_s10_getinternet_no
  Vær:
    entities:
      - sensor.yr_precipitation
      - sensor.yr_symbol
      - sensor.yr_temperature
      - sensor.yr_wind_direction
      - sensor.yr_wind_speed
