version: "2.1"

services:
  home-assistant:
    image: mortenlj/home-assistant-rpi:<%= ENV['HOME_ASSISTANT_VERSION'] %>
    networks:
      - web
    labels:
      - "traefik.backend=home-assistant"
      - "traefik.frontend.rule=Host:home-assistant"
    cap_add:
      - "SYS_RAWIO"
    devices:
      - "/dev/mem"
    volumes:
      - "<%= CONFIG_ROOT %>:/home-assistant"

networks:
  web:
    external:
      name: traefik_webgateway
