version: '2.1'

services:
  proxy:
    image: hypriot/rpi-traefik:v1.3.5
    command: --web --docker --logLevel=INFO
    networks:
      - webgateway
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/traefik/traefik.toml:/traefik.toml
      - /etc/traefik/acme.json:/acme.json

networks:
  webgateway:
    driver: bridge
