apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: homeassistant
  name: homeassistant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Mi
  storageClassName: homeassistant
  volumeMode: Filesystem
  volumeName: homeassistant
