defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
  [entryPoints.http]
  address = ":80"

[acme]
email = "mortenjo+letsencrypt@ifi.uio.no"
storage = "acme.json"
entryPoint = "https"
  [acme.httpChallenge]
  entryPoint = "http"


[[acme.domains]]
   main = "ibidem.homeip.net"


[file]

# rules
[backends]
  [backends.drop]
    [backends.drop.circuitbreaker]
      expression = "NetworkErrorRatio() > 0.1"
    [backends.drop.servers.server1]
    url = "http://localhost:9999"  # Not real
  [backends.emrys]
    [backends.emrys.circuitbreaker]
      expression = "NetworkErrorRatio() > 0.5"
    [backends.emrys.servers.server1]
    url = "http://emrys:80"
  [backends.django]
    [backends.django.circuitbreaker]
      expression = "NetworkErrorRatio() > 0.5"
    [backends.django.servers.server1]
    url = "http://emrys:8300"
  [backends.audio]
    [backends.audio.circuitbreaker]
      expression = "NetworkErrorRatio() > 0.5"
    [backends.audio.servers.server1]
    url = "http://emrys:80"

[frontends]
  [frontends.blocker]
  backend = "drop"
  priority = 10000
    [frontends.blocker.routes.test_1]
    rule = "PathPrefix:/.hg/"
  [frontends.emrys]
  backend = "emrys"
  passHostHeader = true
    [frontends.emrys.routes.test_1]
    rule = "Host:ibidem.homeip.net"
  [frontends.django]
  backend = "django"
  passHostHeader = true
    [frontends.django.routes.test_1]
    rule = "Host:ibidem.homeip.net"
    [frontends.django.routes.test_2]
    rule = "PathPrefix:/django/"
  [frontends.audio]
  backend = "audio"
  passHostHeader = false
    [frontends.audio.routes.test_1]
    rule = "Host:ibidem.homeip.net"
    [frontends.audio.routes.test_2]
    rule = "PathPrefix:/audio/"
